/*
 * Atv Api
 *
 * API de comprobantes electrónicos para la administración tributaria virtual
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fe@hacienda.go.cr
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tribunet.Atv.ApiClient.Api;
using Tribunet.Atv.ApiClient.Model;
using Tribunet.Atv.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tribunet.Atv.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing Comprobante
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComprobanteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Comprobante
        //private Comprobante instance;

        public ComprobanteTests()
        {
            // TODO uncomment below to create an instance of Comprobante
            //instance = new Comprobante();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Comprobante
        /// </summary>
        [Fact]
        public void ComprobanteInstanceTest()
        {
            // TODO uncomment below to test "IsType" Comprobante
            //Assert.IsType<Comprobante>(instance);
        }


        /// <summary>
        /// Test the property 'Clave'
        /// </summary>
        [Fact]
        public void ClaveTest()
        {
            // TODO unit test for the property 'Clave'
        }
        /// <summary>
        /// Test the property 'Fecha'
        /// </summary>
        [Fact]
        public void FechaTest()
        {
            // TODO unit test for the property 'Fecha'
        }
        /// <summary>
        /// Test the property 'Emisor'
        /// </summary>
        [Fact]
        public void EmisorTest()
        {
            // TODO unit test for the property 'Emisor'
        }
        /// <summary>
        /// Test the property 'Receptor'
        /// </summary>
        [Fact]
        public void ReceptorTest()
        {
            // TODO unit test for the property 'Receptor'
        }
        /// <summary>
        /// Test the property 'NotasCredito'
        /// </summary>
        [Fact]
        public void NotasCreditoTest()
        {
            // TODO unit test for the property 'NotasCredito'
        }
        /// <summary>
        /// Test the property 'NotasDebito'
        /// </summary>
        [Fact]
        public void NotasDebitoTest()
        {
            // TODO unit test for the property 'NotasDebito'
        }

    }

}
