/*
 * Atv Api
 *
 * API de comprobantes electrónicos para la administración tributaria virtual
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fe@hacienda.go.cr
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tribunet.Atv.ApiClient.Api;
using Tribunet.Atv.ApiClient.Model;
using Tribunet.Atv.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tribunet.Atv.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing RecepcionGetResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RecepcionGetResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RecepcionGetResponse
        //private RecepcionGetResponse instance;

        public RecepcionGetResponseTests()
        {
            // TODO uncomment below to create an instance of RecepcionGetResponse
            //instance = new RecepcionGetResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecepcionGetResponse
        /// </summary>
        [Fact]
        public void RecepcionGetResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RecepcionGetResponse
            //Assert.IsType<RecepcionGetResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Clave'
        /// </summary>
        [Fact]
        public void ClaveTest()
        {
            // TODO unit test for the property 'Clave'
        }
        /// <summary>
        /// Test the property 'Fecha'
        /// </summary>
        [Fact]
        public void FechaTest()
        {
            // TODO unit test for the property 'Fecha'
        }
        /// <summary>
        /// Test the property 'IndEstado'
        /// </summary>
        [Fact]
        public void IndEstadoTest()
        {
            // TODO unit test for the property 'IndEstado'
        }
        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Fact]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }
        /// <summary>
        /// Test the property 'RespuestaXml'
        /// </summary>
        [Fact]
        public void RespuestaXmlTest()
        {
            // TODO unit test for the property 'RespuestaXml'
        }

    }

}
