/*
 * Atv Api
 *
 * API de comprobantes electrónicos para la administración tributaria virtual
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fe@hacienda.go.cr
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tribunet.Atv.ApiClient.Api;
using Tribunet.Atv.ApiClient.Model;
using Tribunet.Atv.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tribunet.Atv.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing RecepcionPostRequestEmisor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RecepcionPostRequestEmisorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RecepcionPostRequestEmisor
        //private RecepcionPostRequestEmisor instance;

        public RecepcionPostRequestEmisorTests()
        {
            // TODO uncomment below to create an instance of RecepcionPostRequestEmisor
            //instance = new RecepcionPostRequestEmisor();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecepcionPostRequestEmisor
        /// </summary>
        [Fact]
        public void RecepcionPostRequestEmisorInstanceTest()
        {
            // TODO uncomment below to test "IsType" RecepcionPostRequestEmisor
            //Assert.IsType<RecepcionPostRequestEmisor>(instance);
        }


        /// <summary>
        /// Test the property 'TipoIdentificacion'
        /// </summary>
        [Fact]
        public void TipoIdentificacionTest()
        {
            // TODO unit test for the property 'TipoIdentificacion'
        }
        /// <summary>
        /// Test the property 'NumeroIdentificacion'
        /// </summary>
        [Fact]
        public void NumeroIdentificacionTest()
        {
            // TODO unit test for the property 'NumeroIdentificacion'
        }

    }

}
