/*
 * Atv Api
 *
 * API de comprobantes electrónicos para la administración tributaria virtual
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fe@hacienda.go.cr
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tribunet.Atv.ApiClient.Api;
using Tribunet.Atv.ApiClient.Model;
using Tribunet.Atv.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tribunet.Atv.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing RecepcionPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RecepcionPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RecepcionPostRequest
        //private RecepcionPostRequest instance;

        public RecepcionPostRequestTests()
        {
            // TODO uncomment below to create an instance of RecepcionPostRequest
            //instance = new RecepcionPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecepcionPostRequest
        /// </summary>
        [Fact]
        public void RecepcionPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RecepcionPostRequest
            //Assert.IsType<RecepcionPostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Clave'
        /// </summary>
        [Fact]
        public void ClaveTest()
        {
            // TODO unit test for the property 'Clave'
        }
        /// <summary>
        /// Test the property 'Fecha'
        /// </summary>
        [Fact]
        public void FechaTest()
        {
            // TODO unit test for the property 'Fecha'
        }
        /// <summary>
        /// Test the property 'Emisor'
        /// </summary>
        [Fact]
        public void EmisorTest()
        {
            // TODO unit test for the property 'Emisor'
        }
        /// <summary>
        /// Test the property 'Receptor'
        /// </summary>
        [Fact]
        public void ReceptorTest()
        {
            // TODO unit test for the property 'Receptor'
        }
        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Fact]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }
        /// <summary>
        /// Test the property 'ConsecutivoReceptor'
        /// </summary>
        [Fact]
        public void ConsecutivoReceptorTest()
        {
            // TODO unit test for the property 'ConsecutivoReceptor'
        }
        /// <summary>
        /// Test the property 'ComprobanteXml'
        /// </summary>
        [Fact]
        public void ComprobanteXmlTest()
        {
            // TODO unit test for the property 'ComprobanteXml'
        }

    }

}
