/*
 * Atv Api
 *
 * API de comprobantes electrónicos para la administración tributaria virtual
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fe@hacienda.go.cr
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Tribunet.Atv.ApiClient.Client.OpenAPIDateConverter;

namespace Tribunet.Atv.ApiClient.Model
{
    /// <summary>
    /// Comprobante
    /// </summary>
    [DataContract(Name = "Comprobante")]
    public partial class Comprobante : IEquatable<Comprobante>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Comprobante" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Comprobante() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Comprobante" /> class.
        /// </summary>
        /// <param name="clave">clave (required).</param>
        /// <param name="fecha">Fecha de la factura en formato [yyyy-MM-dd&#39;T&#39;HH:mm:ssZ] como se define en [http://tools.ietf.org/html/rfc3339#section-5.6] (date-time). (required).</param>
        /// <param name="emisor">emisor (required).</param>
        /// <param name="receptor">receptor (required).</param>
        /// <param name="notasCredito">notasCredito.</param>
        /// <param name="notasDebito">notasDebito.</param>
        public Comprobante(string clave = default(string), string fecha = default(string), ComprobanteEmisor emisor = default(ComprobanteEmisor), ComprobanteEmisor receptor = default(ComprobanteEmisor), List<ComprobanteNotasCredito> notasCredito = default(List<ComprobanteNotasCredito>), List<ComprobanteNotasCredito> notasDebito = default(List<ComprobanteNotasCredito>))
        {
            this.Clave = clave;
            this.Fecha = fecha;
            // to ensure "emisor" is required (not null)
            if (emisor == null) {
                throw new ArgumentNullException("emisor is a required property for Comprobante and cannot be null");
            }
            this.Emisor = emisor;
            // to ensure "receptor" is required (not null)
            if (receptor == null) {
                throw new ArgumentNullException("receptor is a required property for Comprobante and cannot be null");
            }
            this.Receptor = receptor;
            this.NotasCredito = notasCredito;
            this.NotasDebito = notasDebito;
        }

        /// <summary>
        /// Gets or Sets Clave
        /// </summary>
        [DataMember(Name = "clave", IsRequired = true, EmitDefaultValue = false)]
        public string Clave { get; set; }

        /// <summary>
        /// Fecha de la factura en formato [yyyy-MM-dd&#39;T&#39;HH:mm:ssZ] como se define en [http://tools.ietf.org/html/rfc3339#section-5.6] (date-time).
        /// </summary>
        /// <value>Fecha de la factura en formato [yyyy-MM-dd&#39;T&#39;HH:mm:ssZ] como se define en [http://tools.ietf.org/html/rfc3339#section-5.6] (date-time).</value>
        [DataMember(Name = "fecha", IsRequired = true, EmitDefaultValue = false)]
        public string Fecha { get; set; }

        /// <summary>
        /// Gets or Sets Emisor
        /// </summary>
        [DataMember(Name = "emisor", IsRequired = true, EmitDefaultValue = false)]
        public ComprobanteEmisor Emisor { get; set; }

        /// <summary>
        /// Gets or Sets Receptor
        /// </summary>
        [DataMember(Name = "receptor", IsRequired = true, EmitDefaultValue = false)]
        public ComprobanteEmisor Receptor { get; set; }

        /// <summary>
        /// Gets or Sets NotasCredito
        /// </summary>
        [DataMember(Name = "notasCredito", EmitDefaultValue = false)]
        public List<ComprobanteNotasCredito> NotasCredito { get; set; }

        /// <summary>
        /// Gets or Sets NotasDebito
        /// </summary>
        [DataMember(Name = "notasDebito", EmitDefaultValue = false)]
        public List<ComprobanteNotasCredito> NotasDebito { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Comprobante {\n");
            sb.Append("  Clave: ").Append(Clave).Append("\n");
            sb.Append("  Fecha: ").Append(Fecha).Append("\n");
            sb.Append("  Emisor: ").Append(Emisor).Append("\n");
            sb.Append("  Receptor: ").Append(Receptor).Append("\n");
            sb.Append("  NotasCredito: ").Append(NotasCredito).Append("\n");
            sb.Append("  NotasDebito: ").Append(NotasDebito).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Comprobante);
        }

        /// <summary>
        /// Returns true if Comprobante instances are equal
        /// </summary>
        /// <param name="input">Instance of Comprobante to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Comprobante input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Clave == input.Clave ||
                    (this.Clave != null &&
                    this.Clave.Equals(input.Clave))
                ) && 
                (
                    this.Fecha == input.Fecha ||
                    (this.Fecha != null &&
                    this.Fecha.Equals(input.Fecha))
                ) && 
                (
                    this.Emisor == input.Emisor ||
                    (this.Emisor != null &&
                    this.Emisor.Equals(input.Emisor))
                ) && 
                (
                    this.Receptor == input.Receptor ||
                    (this.Receptor != null &&
                    this.Receptor.Equals(input.Receptor))
                ) && 
                (
                    this.NotasCredito == input.NotasCredito ||
                    this.NotasCredito != null &&
                    input.NotasCredito != null &&
                    this.NotasCredito.SequenceEqual(input.NotasCredito)
                ) && 
                (
                    this.NotasDebito == input.NotasDebito ||
                    this.NotasDebito != null &&
                    input.NotasDebito != null &&
                    this.NotasDebito.SequenceEqual(input.NotasDebito)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Clave != null)
                    hashCode = hashCode * 59 + this.Clave.GetHashCode();
                if (this.Fecha != null)
                    hashCode = hashCode * 59 + this.Fecha.GetHashCode();
                if (this.Emisor != null)
                    hashCode = hashCode * 59 + this.Emisor.GetHashCode();
                if (this.Receptor != null)
                    hashCode = hashCode * 59 + this.Receptor.GetHashCode();
                if (this.NotasCredito != null)
                    hashCode = hashCode * 59 + this.NotasCredito.GetHashCode();
                if (this.NotasDebito != null)
                    hashCode = hashCode * 59 + this.NotasDebito.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // Clave (string) maxLength
            if(this.Clave != null && this.Clave.Length > 50)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Clave, length must be less than 50.", new [] { "Clave" });
            }

            yield break;
        }
    }

}
