/*
 * Atv Api
 *
 * API de comprobantes electrónicos para la administración tributaria virtual
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fe@hacienda.go.cr
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Tribunet.Atv.ApiClient.Client;
using Tribunet.Atv.ApiClient.Api;
// uncomment below to import models
//using Tribunet.Atv.ApiClient.Model;

namespace Tribunet.Atv.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing ComprobanteApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ComprobanteApiTests : IDisposable
    {
        private ComprobanteApi instance;

        public ComprobanteApiTests()
        {
            instance = new ComprobanteApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComprobanteApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ComprobanteApi
            //Assert.IsType<ComprobanteApi>(instance);
        }

        /// <summary>
        /// Test ComprobantesClaveGet
        /// </summary>
        [Fact]
        public void ComprobantesClaveGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clave = null;
            //var response = instance.ComprobantesClaveGet(clave);
            //Assert.IsType<Comprobante>(response);
        }

        /// <summary>
        /// Test ComprobantesGet
        /// </summary>
        [Fact]
        public void ComprobantesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? offset = null;
            //int? limit = null;
            //int? emisor = null;
            //string receptor = null;
            //var response = instance.ComprobantesGet(offset, limit, emisor, receptor);
            //Assert.IsType<List<Comprobante>>(response);
        }
    }
}
