/*
 * Atv Api
 *
 * API de comprobantes electrónicos para la administración tributaria virtual
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fe@hacienda.go.cr
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Tribunet.Atv.ApiClient.Client;
using Tribunet.Atv.ApiClient.Api;
// uncomment below to import models
//using Tribunet.Atv.ApiClient.Model;

namespace Tribunet.Atv.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing RecepcionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RecepcionApiTests : IDisposable
    {
        private RecepcionApi instance;

        public RecepcionApiTests()
        {
            instance = new RecepcionApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecepcionApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' RecepcionApi
            //Assert.IsType<RecepcionApi>(instance);
        }

        /// <summary>
        /// Test GetReception
        /// </summary>
        [Fact]
        public void GetReceptionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clave = null;
            //var response = instance.GetReception(clave);
            //Assert.IsType<RecepcionGetResponse>(response);
        }

        /// <summary>
        /// Test PostReception
        /// </summary>
        [Fact]
        public void PostReceptionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RecepcionPostRequest recepcionPostRequest = null;
            //instance.PostReception(recepcionPostRequest);
        }
    }
}
