//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Tribunet.Atv.Models.MensajeHacienda_V4_2 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeHacienda")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeHacienda", IsNullable=false)]
    public partial class MensajeHacienda {
        
        private string claveField;
        
        private string nombreEmisorField;
        
        private MensajeHaciendaTipoIdentificacionEmisor tipoIdentificacionEmisorField;
        
        private string numeroCedulaEmisorField;
        
        private string nombreReceptorField;
        
        private MensajeHaciendaTipoIdentificacionReceptor tipoIdentificacionReceptorField;
        
        private bool tipoIdentificacionReceptorFieldSpecified;
        
        private string numeroCedulaReceptorField;
        
        private MensajeHaciendaMensaje mensajeField;
        
        private string detalleMensajeField;
        
        private decimal montoTotalImpuestoField;
        
        private bool montoTotalImpuestoFieldSpecified;
        
        private decimal totalFacturaField;
        
        /// <remarks/>
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        public string NombreEmisor {
            get {
                return this.nombreEmisorField;
            }
            set {
                this.nombreEmisorField = value;
            }
        }
        
        /// <remarks/>
        public MensajeHaciendaTipoIdentificacionEmisor TipoIdentificacionEmisor {
            get {
                return this.tipoIdentificacionEmisorField;
            }
            set {
                this.tipoIdentificacionEmisorField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroCedulaEmisor {
            get {
                return this.numeroCedulaEmisorField;
            }
            set {
                this.numeroCedulaEmisorField = value;
            }
        }
        
        /// <remarks/>
        public string NombreReceptor {
            get {
                return this.nombreReceptorField;
            }
            set {
                this.nombreReceptorField = value;
            }
        }
        
        /// <remarks/>
        public MensajeHaciendaTipoIdentificacionReceptor TipoIdentificacionReceptor {
            get {
                return this.tipoIdentificacionReceptorField;
            }
            set {
                this.tipoIdentificacionReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipoIdentificacionReceptorSpecified {
            get {
                return this.tipoIdentificacionReceptorFieldSpecified;
            }
            set {
                this.tipoIdentificacionReceptorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string NumeroCedulaReceptor {
            get {
                return this.numeroCedulaReceptorField;
            }
            set {
                this.numeroCedulaReceptorField = value;
            }
        }
        
        /// <remarks/>
        public MensajeHaciendaMensaje Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string DetalleMensaje {
            get {
                return this.detalleMensajeField;
            }
            set {
                this.detalleMensajeField = value;
            }
        }
        
        /// <remarks/>
        public decimal MontoTotalImpuesto {
            get {
                return this.montoTotalImpuestoField;
            }
            set {
                this.montoTotalImpuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MontoTotalImpuestoSpecified {
            get {
                return this.montoTotalImpuestoFieldSpecified;
            }
            set {
                this.montoTotalImpuestoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalFactura {
            get {
                return this.totalFacturaField;
            }
            set {
                this.totalFacturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeHacienda")]
    public enum MensajeHaciendaTipoIdentificacionEmisor {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeHacienda")]
    public enum MensajeHaciendaTipoIdentificacionReceptor {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeHacienda")]
    public enum MensajeHaciendaMensaje {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
}
